services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    image: mohamedkhalilzrelly/mernubs:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      CORS_ORIGIN: ${CORS_ORIGIN}
      PORT: ${PORT}
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    image: mohamedkhalilzrelly/mernufs:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mongo_data:
